; PlatformIO Project Configuration File

[env:esp32_c3_supermini]
platform = espressif32
; The common ESP32-C3 SuperMini uses the ESP32-C3-DevKitM-1-compatible target.
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200

lib_deps =
    https://github.com/DFRobot/DFRobot_DF1201S.git

; Low power configuration for battery operation
board_build.f_cpu = 80000000L

build_flags =
    -Iinclude
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
